# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  "php-7.1":
    docker:
      - image: circleci/php:7.1.30
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install bcmath
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer self-update --stable --no-interaction
      - run: composer install --no-suggest --no-interaction --prefer-dist
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer clover
      - run: ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
  "php-7.2":
    docker:
      - image: circleci/php:7.2.20
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install bcmath
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer self-update --stable --no-interaction
      - run: composer install --no-suggest --no-interaction --prefer-dist
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer clover
      - run: ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
  "php-7.3":
    docker:
      - image: circleci/php:7.3.7
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install bcmath
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v2-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: composer self-update --stable --no-interaction
      - run: composer install --no-suggest --no-interaction --prefer-dist
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - save_cache:
          key: v2-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer clover
      - run: ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  version: 2
  build_and_test:
    jobs:
      - "php-7.1"
      - "php-7.2"
      - "php-7.3"
